apiVersion: v1
kind: Service
metadata:
  name: ifs-reportbuilder-svc
  namespace: control-plane
spec:
  type: NodePort
  selector:
    app: ifs-reportbuilder-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31702
      nodePort: 31702
