kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-kafka
  labels:
    type: local
    app: kafka
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: "/home/ifserveradmn/if-studio/kafka-data"