apiVersion: v1
kind: Service
metadata:
  name: ifs-gensis-app-svc
  namespace: control-plane
spec:
  type: NodePort
  selector:
    app: ifs-gensis-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31512
      nodePort: 31512
