apiVersion: v1
kind: Service
metadata:
  name: ifa-odata-svc-svc
  namespace: control-plane
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: ifa-odata-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31513
      nodePort: 31513
