version: '3.3'
services:
    keycloak-postgres:
        container_name: keycloak_postgres
        networks:
            - keycloak-network
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=eePheuT7ie
        image: postgres
    keycloak:
	container_name: keycloak
        networks:
            - keycloak-network
        environment:
            - DB_ADDR=keycloak_postgres
            - DB_PORT=5432
            - DB_VENDOR=postgres
            - JDBC_PARAMS='connectTimeout=30'
            - DB_USER=keycloak
            - DB_PASSWORD=eePheuT7ie
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin123
        image: jboss/keycloak
        ports:
            - '8443:8443'

networks:
    keycloak-network: {}
