apiVersion: v1
kind: Service
metadata:
  name: fs-bulk-manager-svc
  namespace: control-plane
spec:
  selector:
    app: fs-bulk-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31551
