apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifa-notification-mgr
  namespace: control-plane
  labels:
    app: ifa-notification-mgr
    domain: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifa-notification-mgr
  template:
    metadata:
      labels:
        app: ifa-notification-mgr
    spec:
      containers:
      - name: ifa-notification-mgr
        image: intelliflow/ifa-notification-mgr:colo
        imagePullPolicy: Always
        ports:
        - containerPort: 31601
        env:
        - name: COLO_MONGO_HOST
          valueFrom:
            configMapKeyRef:   
              name: ifa-notification-mgr-cm  
              key: COLO_MONGO_HOST
        - name: COLO_MONGO_NAME
          valueFrom:
            configMapKeyRef:   
              name: ifa-notification-mgr-cm  
              key: COLO_MONGO_NAME
        - name: COLO_MONGO_PORT
          valueFrom:
            configMapKeyRef:   
              name: ifa-notification-mgr-cm  
              key: COLO_MONGO_PORT
        - name: COLO_MONGO_USERNAME
          valueFrom:
            configMapKeyRef:   
              name: ifa-notification-mgr-cm  
              key: COLO_MONGO_USERNAME
        - name: COLO_MONGO_PASSWORD
          valueFrom:
            configMapKeyRef:   
              name: ifa-notification-mgr-cm  
              key: COLO_MONGO_PASSWORD
        - name: COLO_PORT
          valueFrom:
            configMapKeyRef:   
              name: ifa-notification-mgr-cm  
              key: COLO_PORT
        # ENV example to mount configmap as env
        # env:
        # - name: KEY_NAME
        #   valueFrom:
        #     configMapKeyRef:   
        #       name: ifa-notification-mgr-cm  
        #       key: key-from-cm

        # Volume example to mount configmap as file
  #       volumeMounts:
  #       - name: ifa-notification-mgr-cm
  #         mountPath: /etc/config
  # volumes:
  #   - name: ifa-notification-mgr-cm
  #     configMap:
  #       name: ifa-notification-mgr-cm