kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-mongodb
  labels:
    type: local
    app: mongodb
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: "/home/ifserveradmn/if-studio/mongodb-data"