apiVersion: v1
kind: Service
metadata:
  name: ifs-cds-mgr-svc
  namespace: control-plane
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: ifs-cds-mgr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31524
      nodePort: 31524
