apiVersion: v1
kind: Service
metadata:
  name: ifs-process-mgr-svc
  namespace: control-plane
spec:
  type: NodePort
  selector:
    app: ifs-process-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31701
      nodePort: 31701
