apiVersion: v1
kind: Service
metadata:
  name: ifs-router-svc-svc
  namespace: control-plane
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: ifs-router-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31600
      nodePort: 31600
