apiVersion: v1
kind: Service
metadata:
  name: ifs-bpmn-validator-svc
  namespace: control-plane
spec:
  selector:
    app: ifs-bpmn-validator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 31502
