kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-zookeeper
  labels:
    type: local
    app: zookeeper
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: "/home/ifserveradmn/if-studio/zookeeper-data"