apiVersion: v1
kind: ConfigMap
metadata:
  name: if-identity-mgr-cm
  namespace: control-plane
data:
  KEYCLOAK_URL: "https://kc-colo.intelliflow.ai/"
  PORT: "31523"
  # example of a simple property defined using --from-literal
  # example.property.1: hello
  # example.property.2: world
  # example of a complex property defined using --from-file
  # example.property.file: |-
  #   property.1=value-1
  #   property.2=value-2
  #   property.3=value-3 